import zoneinfo
from modules.dataclass import KeibaType, LocationInfo, LocationName

LOCATIONS_INFO: dict[LocationName, LocationInfo] = {
    LocationName.SAPPORO: LocationInfo(
        name="札幌競馬場",
        address="〒060-0016, 北海道札幌市中央区, 北16条西16-1-1",
        geo="43.076045,141.323257",
        admission="https://jra-tickets.jp/",
        reservation="https://jra-tickets.jp/",
        betting="https://www.ipat.jra.go.jp/",
        youtube_channel_id="jraofficial",
        keiba_type=KeibaType.JRA,
        netkeiba_id=1,
    ),
    LocationName.HAKODATE: LocationInfo(
        name="函館競馬場",
        address="〒042-8585, 北海道函館市, 駒場町12-2",
        geo="41.783556,140.775696",
        admission="https://jra-tickets.jp/",
        reservation="https://jra-tickets.jp/",
        betting="https://www.ipat.jra.go.jp/",
        youtube_channel_id="jraofficial",
        keiba_type=KeibaType.JRA,
        netkeiba_id=2,
    ),
    LocationName.FUKUSHIMA: LocationInfo(
        name="福島競馬場",
        address="〒960-8114, 福島県福島市, 松浪町9-23",
        geo="37.764036,140.479352",
        admission="https://jra-tickets.jp/",
        reservation="https://jra-tickets.jp/",
        betting="https://www.ipat.jra.go.jp/",
        youtube_channel_id="jraofficial",
        keiba_type=KeibaType.JRA,
        netkeiba_id=3,
    ),
    LocationName.NIIGATA: LocationInfo(
        name="新潟競馬場",
        address="〒950-3301, 新潟県新潟市北区, 笹山3490",
        geo="37.948938,139.183418",
        admission="https://jra-tickets.jp/",
        reservation="https://jra-tickets.jp/",
        betting="https://www.ipat.jra.go.jp/",
        youtube_channel_id="jraofficial",
        keiba_type=KeibaType.JRA,
        netkeiba_id=4,
    ),
    LocationName.TOKYO: LocationInfo(
        name="東京競馬場",
        address="〒183-0024, 東京都府中市, 日吉町1-1",
        geo="35.664474,139.480346",
        admission="https://jra-tickets.jp/",
        reservation="https://jra-tickets.jp/",
        betting="https://www.ipat.jra.go.jp/",
        youtube_channel_id="jraofficial",
        keiba_type=KeibaType.JRA,
        netkeiba_id=5,
    ),
    LocationName.NAKAYAMA: LocationInfo(
        name="中山競馬場",
        address="〒273-0037, 千葉県船橋市, 古作1-1-1",
        geo="35.727043,139.959520",
        admission="https://jra-tickets.jp/",
        reservation="https://jra-tickets.jp/",
        betting="https://www.ipat.jra.go.jp/",
        youtube_channel_id="jraofficial",
        keiba_type=KeibaType.JRA,
        netkeiba_id=6,
    ),
    LocationName.CHUKYO: LocationInfo(
        name="中京競馬場",
        address="〒470-1132, 愛知県豊明市間米町, 敷田1225",
        geo="35.065468,136.987098",
        admission="https://jra-tickets.jp/",
        reservation="https://jra-tickets.jp/",
        betting="https://www.ipat.jra.go.jp/",
        youtube_channel_id="jraofficial",
        keiba_type=KeibaType.JRA,
        netkeiba_id=7,
    ),
    LocationName.KYOTO: LocationInfo(
        name="京都競馬場",
        address="〒612-8265, 京都府京都市伏見区, 葭島渡場島町32",
        geo="34.907831,135.724072",
        admission="https://jra-tickets.jp/",
        reservation="https://jra-tickets.jp/",
        betting="https://www.ipat.jra.go.jp/",
        youtube_channel_id="jraofficial",
        keiba_type=KeibaType.JRA,
        netkeiba_id=8,
    ),
    LocationName.HANSHIN: LocationInfo(
        name="阪神競馬場",
        address="〒665-0053, 兵庫県宝塚市, 駒の町1-1",
        geo="34.777831,135.360592",
        admission="https://jra-tickets.jp/",
        reservation="https://jra-tickets.jp/",
        betting="https://www.ipat.jra.go.jp/",
        youtube_channel_id="jraofficial",
        keiba_type=KeibaType.JRA,
        netkeiba_id=9,
    ),
    LocationName.KOKURA: LocationInfo(
        name="小倉競馬場",
        address="〒802-0841, 福岡県北九州市小倉南区, 北方4-5-1",
        geo="33.843143,130.876244",
        admission="https://jra-tickets.jp/",
        reservation="https://jra-tickets.jp/",
        betting="https://www.ipat.jra.go.jp/",
        youtube_channel_id="jraofficial",
        keiba_type=KeibaType.JRA,
        netkeiba_id=10,
    ),
    LocationName.OBIHIRO: LocationInfo(
        name="帯広競馬場",
        address="〒080-0023, 北海道帯広市西13条, 南9-1",
        geo="42.921079,143.183481",
        admission="https://banei-keiba.or.jp/access.php",
        reservation="https://banei-keiba.or.jp/spot_premiumlounge.php",
        live="https://www.youtube.com/@user-di2dh2dc4q/streams",
        youtube_channel_id="user-di2dh2dc4q",
        keiba_type=KeibaType.NAR,
        netkeiba_id=65,
        keibago_babacode=3,
    ),
    LocationName.MONBETSU: LocationInfo(
        name="門別競馬場",
        address="〒055-0008, 北海道沙流郡日高町, 富川駒丘76-1",
        geo="42.538360,141.997367",
        admission="http://www.hokkaidokeiba.net/guide/access/fbus.php",
        betting="https://n.ipat.jra.go.jp",
        live="https://www.youtube.com/@live2820/streams",
        youtube_channel_id="live2820",
        keiba_type=KeibaType.NAR,
        netkeiba_id=30,
        keibago_babacode=36,
    ),
    LocationName.MORIOKA: LocationInfo(
        name="盛岡競馬場",
        address="〒020-0803, 岩手県盛岡市新庄, 上八木田10-10-4",
        geo="39.696113,141.221176",
        admission="https://www.iwatekeiba.or.jp/race/free_bus",
        reservation="https://www.google.com/search?q=site:www.iwatekeiba.or.jp/news+指定席",
        betting="https://n.ipat.jra.go.jp",
        live="https://www.youtube.com/@IwateKeibaITV/streams",
        youtube_channel_id="IwateKeibaITV",
        keiba_type=KeibaType.NAR,
        netkeiba_id=35,
        keibago_babacode=10,
    ),
    LocationName.MIZUSAWA: LocationInfo(
        name="水沢競馬場",
        address="〒023-0831, 岩手県奥州市水沢姉体町, 阿久戸1-2",
        geo="39.130318,141.166911",
        admission="https://www.iwatekeiba.or.jp/race/free_bus",
        betting="https://n.ipat.jra.go.jp",
        live="https://www.youtube.com/@IwateKeibaITV/streams",
        youtube_channel_id="IwateKeibaITV",
        keiba_type=KeibaType.NAR,
        netkeiba_id=36,
        keibago_babacode=11,
    ),
    LocationName.URAWA: LocationInfo(
        name="浦和競馬場",
        address="〒336-0016, 埼玉県さいたま市南区, 大谷場1-8-42",
        geo="35.855503,139.669410",
        admission="https://www.urawa-keiba.jp/navi/facility03.html#number02",
        reservation="https://www.google.com/search?q=site:keiba.rakuten.co.jp+%22浦和競馬%22+%22入場%22",
        betting="https://n.ipat.jra.go.jp",
        live="https://www.youtube.com/@浦和競馬公式/streams",
        youtube_channel_id="浦和競馬公式",
        keiba_type=KeibaType.NAR,
        netkeiba_id=42,
        keibago_babacode=18,
    ),
    LocationName.FUNABASHI: LocationInfo(
        name="船橋競馬場",
        address="〒273-0013, 千葉県船橋市, 若松1-2-1",
        geo="35.688094,139.994934",
        admission="https://www.f-keiba.com/guide/",
        reservation="https://www.google.com/search?q=site:blog.f-keiba.com+%22入場%22",
        betting="https://n.ipat.jra.go.jp",
        live="https://www.youtube.com/@funabashi-keiba/streams",
        youtube_channel_id="funabashi-keiba",
        keiba_type=KeibaType.NAR,
        netkeiba_id=43,
        keibago_babacode=19,
    ),
    LocationName.OI: LocationInfo(
        name="大井競馬場",
        address="〒140-0012, 東京都品川区, 勝島2-1-2",
        geo="35.595758,139.744662",
        admission="https://www.tokyocitykeiba.com/guide/about_tck/",
        reservation="https://www.tokyocitykeiba.com/reservedseat/buying_guide/",
        betting="https://n.ipat.jra.go.jp",
        live="https://www.youtube.com/@tckkeiba/streams",
        youtube_channel_id="tckkeiba",
        keiba_type=KeibaType.NAR,
        netkeiba_id=44,
        keibago_babacode=20,
    ),
    LocationName.KAWASAKI: LocationInfo(
        name="川崎競馬場",
        address="〒210-0011, 神奈川県川崎市川崎区, 富士見1-5-1",
        geo="35.534072,139.710847",
        admission="https://www.kawasaki-keiba.jp/info/business_day/",
        reservation="https://www.kawasaki-keiba.jp/seat/reserved/",
        betting="https://n.ipat.jra.go.jp",
        live="https://www.youtube.com/@公式川崎競馬/streams",
        youtube_channel_id="公式川崎競馬",
        keiba_type=KeibaType.NAR,
        netkeiba_id=45,
        keibago_babacode=21,
    ),
    LocationName.KANAZAWA: LocationInfo(
        name="金沢競馬場",
        address="〒920-3105, 石川県金沢市八田町, 西1 金沢競馬場",
        geo="36.634042,136.673253",
        admission="https://www.kanazawakeiba.com/facilities/outline/",
        reservation="https://www.google.com/search?q=site:www.kanazawakeiba.com+指定席",
        betting="https://n.ipat.jra.go.jp",
        live="https://www.youtube.com/@金沢競馬公式チャンネル/streams",
        youtube_channel_id="金沢競馬公式チャンネル",
        keiba_type=KeibaType.NAR,
        netkeiba_id=46,
        keibago_babacode=22,
    ),
    LocationName.KASAMATSU: LocationInfo(
        name="笠松競馬場",
        address="〒501-6036, 岐阜県羽島郡笠松町, 若葉町12",
        geo="35.372466,136.765175",
        admission="https://www.kasamatsu-keiba.com/facilities",
        reservation="https://www.google.com/search?q=site:www.kasamatsu-keiba.com+有料席",
        betting="https://n.ipat.jra.go.jp",
        live="https://www.youtube.com/@笠松けいばレース映像配信チャ/streams",
        youtube_channel_id="笠松けいばレース映像配信チャ",
        keiba_type=KeibaType.NAR,
        netkeiba_id=47,
        keibago_babacode=23,
    ),
    LocationName.NAGOYA: LocationInfo(
        name="名古屋競馬場",
        address="〒498-0065, 愛知県弥富市, 駒野町1",
        geo="35.055350,136.785048",
        admission="https://www.nagoyakeiba.com/guide/information.html",
        reservation="https://www.nagoyakeiba.com/reservation/index.html",
        betting="https://n.ipat.jra.go.jp",
        live="https://www.youtube.com/@金シャチけいば情報/streams",
        youtube_channel_id="金シャチけいば情報",
        keiba_type=KeibaType.NAR,
        netkeiba_id=48,
        keibago_babacode=24,
    ),
    LocationName.SONODA: LocationInfo(
        name="園田競馬場",
        address="〒661-0951, 兵庫県尼崎市, 田能2-1-1",
        geo="34.764694,135.445509",
        admission="https://www.sonoda-himeji.jp/guide/sbet",
        reservation="https://www.google.com/search?q=site:www.sonoda-himeji.jp+園田競馬場+指定席",
        betting="https://n.ipat.jra.go.jp",
        live="https://www.youtube.com/@sonodahimejiweb/streams",
        youtube_channel_id="sonodahimejiweb",
        keiba_type=KeibaType.NAR,
        netkeiba_id=50,
        keibago_babacode=27,
    ),
    LocationName.HIMEJI: LocationInfo(
        name="姫路競馬場",
        address="〒670-0882, 兵庫県姫路市, 広峰2-7-80",
        geo="34.855566,134.704458",
        admission="https://www.sonoda-himeji.jp/guide/hbet",
        reservation="https://www.google.com/search?q=site:www.sonoda-himeji.jp+姫路競馬場+指定席",
        betting="https://n.ipat.jra.go.jp",
        live="https://www.youtube.com/@sonodahimejiweb/streams",
        youtube_channel_id="sonodahimejiweb",
        keiba_type=KeibaType.NAR,
        netkeiba_id=51,
        keibago_babacode=28,
    ),
    LocationName.KOCHI: LocationInfo(
        name="高知競馬場",
        address="〒781-0271, 高知県高知市長浜, 宮田2000",
        geo="33.504549,133.528300",
        admission="https://www.keiba.or.jp/?cat=74",
        reservation="https://www.google.com/search?q=site:www.keiba.or.jp+特別観覧席",
        betting="https://n.ipat.jra.go.jp",
        live="https://www.youtube.com/@KeibaOrJp/streams",
        youtube_channel_id="KeibaOrJp",
        keiba_type=KeibaType.NAR,
        netkeiba_id=54,
        keibago_babacode=31,
    ),
    LocationName.SAGA: LocationInfo(
        name="佐賀競馬場",
        address="〒841-0073, 佐賀県鳥栖市, 江島町字西谷3256-228",
        geo="33.350995,130.469143",
        admission="https://www.sagakeiba.net/guide/#map02",
        reservation="https://www.sagakeiba.net/guide/?id=tab2",
        betting="https://n.ipat.jra.go.jp",
        live="https://www.youtube.com/@sagakeibaofficial/streams",
        youtube_channel_id="sagakeibaofficial",
        keiba_type=KeibaType.NAR,
        netkeiba_id=55,
        keibago_babacode=32,
    ),
    LocationName.SHA_TIN: LocationInfo(
        name="Sha Tin Racecourse",
        address="Sha Tin, New Territories, Hong Kong SAR, China",
        geo="22.400634, 114.204179",
        betting="https://www.ipat.jra.go.jp/",
        live="https://sp.gch.jp/",
        youtube_channel_id="jraofficial",
        flag="🇭🇰",
        keiba_type=KeibaType.OVERSEAS,
        netkeiba_id="H1",
        timezone=zoneinfo.ZoneInfo("Asia/Hong_Kong"),
    ),
    LocationName.PARIS_LONGCHAMP: LocationInfo(
        name="Longchamp Racecourse",
        address="2 Route des Tribunes, 75016 Paris, France",
        geo="48.860889, 2.231523",
        betting="https://www.ipat.jra.go.jp/",
        live="https://sp.gch.jp/",
        youtube_channel_id="jraofficial",
        flag="🇫🇷",
        keiba_type=KeibaType.OVERSEAS,
        netkeiba_id="C8",
        timezone=zoneinfo.ZoneInfo("Europe/Paris"),
    ),
    LocationName.DEAUVILLE: LocationInfo(
        name="Deauville-La Touques Racecourse",
        address="45 Avenue Hocquart de Turtot, 14800 Deauville, France",
        geo="49.353256, 0.073450",
        betting="https://www.ipat.jra.go.jp/",
        live="https://sp.gch.jp/",
        youtube_channel_id="jraofficial",
        flag="🇫🇷",
        keiba_type=KeibaType.OVERSEAS,
        netkeiba_id="C4",
        timezone=zoneinfo.ZoneInfo("Europe/Paris"),
    ),
    LocationName.CHANTILLY: LocationInfo(
        name="Chantilly Racecourse",
        address="Route des Aigles & Avenue de la Plaine des Aigles, 60500 Chantilly, France",
        geo="49.190400, 2.474290",
        betting="https://www.ipat.jra.go.jp/",
        live="https://sp.gch.jp/",
        youtube_channel_id="jraofficial",
        flag="🇫🇷",
        keiba_type=KeibaType.OVERSEAS,
        netkeiba_id="C5",
        timezone=zoneinfo.ZoneInfo("Europe/Paris"),
    ),
    LocationName.MEYDAN: LocationInfo(
        name="Meydan Racecourse",
        address="Al Meydan St 10, Dubai, United Arab Emirates",
        geo="25.156783, 55.304833",
        betting="https://www.ipat.jra.go.jp/",
        live="https://sp.gch.jp/",
        youtube_channel_id="jraofficial",
        flag="🇯🇴",
        keiba_type=KeibaType.OVERSEAS,
        netkeiba_id="J0",
        timezone=zoneinfo.ZoneInfo("Asia/Dubai"),
    ),
    LocationName.DEL_MAR: LocationInfo(
        name="Del Mar Racetrack",
        address="2260 Jimmy Durante Blvd, Del Mar, CA 92014, United States",
        geo="32.976304, -117.262959",
        betting="https://www.ipat.jra.go.jp/",
        live="https://sp.gch.jp/",
        youtube_channel_id="jraofficial",
        flag="🇺🇸",
        keiba_type=KeibaType.OVERSEAS,
        netkeiba_id="FP",
        timezone=zoneinfo.ZoneInfo("America/Los_Angeles"),
    ),
    LocationName.CHURCHILL_DOWNS: LocationInfo(
        name="Churchill Downs",
        address="700 Central Ave, Louisville, KY 40208, United States",
        geo="38.202711, -85.770221",
        betting="https://www.ipat.jra.go.jp/",
        live="https://sp.gch.jp/",
        youtube_channel_id="jraofficial",
        flag="🇺🇸",
        keiba_type=KeibaType.OVERSEAS,
        netkeiba_id="F4",
        timezone=zoneinfo.ZoneInfo("America/Kentucky/Louisville"),
    ),
    LocationName.PIMLICO: LocationInfo(
        name="Pimlico Race Course",
        address="5201 Park Heights Ave, Baltimore, MD 21215, United States",
        geo="39.353331, -76.673026",
        betting="https://www.ipat.jra.go.jp/",
        live="https://sp.gch.jp/",
        youtube_channel_id="jraofficial",
        flag="🇺🇸",
        keiba_type=KeibaType.OVERSEAS,
        netkeiba_id="FJ",
        timezone=zoneinfo.ZoneInfo("America/New_York"),
    ),
    LocationName.SARATOGA: LocationInfo(
        name="Saratoga Race Course",
        address="267 Union Ave, Saratoga Springs, NY 12866, United States",
        geo="43.073465, -73.769782",
        betting="https://www.ipat.jra.go.jp/",
        live="https://sp.gch.jp/",
        youtube_channel_id="jraofficial",
        flag="🇺🇸",
        keiba_type=KeibaType.OVERSEAS,
        netkeiba_id="FE",
        timezone=zoneinfo.ZoneInfo("America/New_York"),
    ),
    LocationName.SANTA_ANITA_PARK: LocationInfo(
        name="Santa Anita Park Racetrack",
        address="285 W Huntington Dr, Arcadia, CA 91007, United States",
        geo="34.138920, -118.045285",
        betting="https://www.ipat.jra.go.jp/",
        live="https://sp.gch.jp/",
        youtube_channel_id="jraofficial",
        flag="🇺🇸",
        keiba_type=KeibaType.OVERSEAS,
        netkeiba_id="F3",
        timezone=zoneinfo.ZoneInfo("America/Los_Angeles"),
    ),
    LocationName.BELMONT_PARK: LocationInfo(
        name="Belmont Park",
        address="2150 Hempstead Turnpike, Elmont, NY 11003, United States",
        geo="40.714956, -73.722065",
        betting="https://www.ipat.jra.go.jp/",
        live="https://sp.gch.jp/",
        youtube_channel_id="jraofficial",
        flag="🇺🇸",
        keiba_type=KeibaType.OVERSEAS,
        netkeiba_id="FD",
        timezone=zoneinfo.ZoneInfo("America/New_York"),
    ),
    LocationName.RANDWICK: LocationInfo(
        name="Royal Randwick Racecourse",
        address="Ascot St, Randwick NSW 2031, Australia",
        geo="-33.910455, 151.230231",
        betting="https://www.ipat.jra.go.jp/",
        live="https://sp.gch.jp/",
        youtube_channel_id="jraofficial",
        flag="🇦🇺",
        keiba_type=KeibaType.OVERSEAS,
        netkeiba_id="GE",
        timezone=zoneinfo.ZoneInfo("Australia/Sydney"),
    ),
    LocationName.MOONEE_VALLEY: LocationInfo(
        name="Moonee Valley Racing Club",
        address="Feehan Ave, Moonee Ponds VIC 3039, Australia",
        geo="-37.763436, 144.930463",
        betting="https://www.ipat.jra.go.jp/",
        live="https://sp.gch.jp/",
        youtube_channel_id="jraofficial",
        flag="🇦🇺",
        keiba_type=KeibaType.OVERSEAS,
        netkeiba_id="G5",
        timezone=zoneinfo.ZoneInfo("Australia/Melbourne"),
    ),
    LocationName.FLEMINGTON: LocationInfo(
        name="Flemington Racecourse",
        address="448 Epsom Rd, Flemington VIC 3031, Australia",
        geo="-37.788539, 144.911756",
        betting="https://www.ipat.jra.go.jp/",
        live="https://sp.gch.jp/",
        youtube_channel_id="jraofficial",
        flag="🇦🇺",
        keiba_type=KeibaType.OVERSEAS,
        netkeiba_id="G4",
        timezone=zoneinfo.ZoneInfo("Australia/Melbourne"),
    ),
    LocationName.CAULFIELD: LocationInfo(
        name="Caulfield Racecourse",
        address="Station Street, Caulfield East VIC 3145, Australia",
        geo="-37.881634, 145.039505",
        betting="https://www.ipat.jra.go.jp/",
        live="https://sp.gch.jp/",
        youtube_channel_id="jraofficial",
        flag="🇦🇺",
        keiba_type=KeibaType.OVERSEAS,
        netkeiba_id="G6",
        timezone=zoneinfo.ZoneInfo("Australia/Melbourne"),
    ),
    LocationName.ASCOT: LocationInfo(
        name="Ascot Racecourse",
        address="High Street, Ascot, SL5 7JX, England",
        geo="51.412203, -0.679350",
        betting="https://www.ipat.jra.go.jp/",
        live="https://sp.gch.jp/",
        youtube_channel_id="jraofficial",
        flag="🇬🇧",
        keiba_type=KeibaType.OVERSEAS,
        netkeiba_id="A0",
        timezone=zoneinfo.ZoneInfo("Europe/London"),
    ),
    LocationName.YORK: LocationInfo(
        name="York Racecourse",
        address="Knavesmire Road, York, YO23 1EX, England",
        geo="53.940591, -1.092324",
        betting="https://www.ipat.jra.go.jp/",
        live="https://sp.gch.jp/",
        youtube_channel_id="jraofficial",
        flag="🇬🇧",
        keiba_type=KeibaType.OVERSEAS,
        netkeiba_id="AH",
        timezone=zoneinfo.ZoneInfo("Europe/London"),
    ),
    LocationName.SANDOWN: LocationInfo(
        name="Sandown Park Racecourse",
        address="Portsmouth Road, Esher, KT10 9AJ, England",
        geo="51.373665, -0.362820",
        betting="https://www.ipat.jra.go.jp/",
        live="https://sp.gch.jp/",
        youtube_channel_id="jraofficial",
        flag="🇬🇧",
        keiba_type=KeibaType.OVERSEAS,
        netkeiba_id="A3",
        timezone=zoneinfo.ZoneInfo("Europe/London"),
    ),
    LocationName.GOODWOOD: LocationInfo(
        name="Goodwood Racecourse",
        address="Chichester, PO18 0PS, England",
        geo="50.891997, -0.744264",
        betting="https://www.ipat.jra.go.jp/",
        live="https://sp.gch.jp/",
        youtube_channel_id="jraofficial",
        flag="🇬🇧",
        keiba_type=KeibaType.OVERSEAS,
        netkeiba_id="AF",
        timezone=zoneinfo.ZoneInfo("Europe/London"),
    ),
    LocationName.EPSOM_DOWNS: LocationInfo(
        name="Epsom Downs Racecourse",
        address="Surrey, KT18 5LQ, England",
        geo="51.313338, -0.255605",
        betting="https://www.ipat.jra.go.jp/",
        live="https://sp.gch.jp/",
        youtube_channel_id="jraofficial",
        flag="🇬🇧",
        keiba_type=KeibaType.OVERSEAS,
        netkeiba_id="A1",
        timezone=zoneinfo.ZoneInfo("Europe/London"),
    ),
    LocationName.LEOPARDSTOWN: LocationInfo(
        name="Leopardstown Racecourse",
        address="Leopardstown Pavilion, Leopardstown Racecourse, Dublin 18, D18 Y9T1, Ireland",
        geo="53.266490, -6.193322",
        betting="https://www.ipat.jra.go.jp/",
        live="https://sp.gch.jp/",
        youtube_channel_id="jraofficial",
        flag="🇮🇪",
        keiba_type=KeibaType.OVERSEAS,
        netkeiba_id="B1",
        timezone=zoneinfo.ZoneInfo("Europe/Dublin"),
    ),
    LocationName.KING_ABDULAZIZ: LocationInfo(
        name="King Abdulaziz Equestrian Field",
        address="13638, Rumah, Saudi Arabia",
        geo="24.986442, 46.786329",
        betting="https://www.ipat.jra.go.jp/",
        live="https://sp.gch.jp/",
        youtube_channel_id="jraofficial",
        flag="🇸🇦",
        keiba_type=KeibaType.OVERSEAS,
        netkeiba_id="P0",
        timezone=zoneinfo.ZoneInfo("Asia/Riyadh"),
    ),
    LocationName.AL_RAYYAN: LocationInfo(
        name="Qatar Racing and Equestrian Club",
        address="Building Number 104, Al Qalah Street, Zone 53, Al Rayyan, Qatar",
        geo="25.282974, 51.430688",
        live="https://sp.gch.jp/",
        youtube_channel_id="jraofficial",
        flag="🇶🇦",
        keiba_type=KeibaType.OVERSEAS,
        netkeiba_id="M8",
        timezone=zoneinfo.ZoneInfo("Asia/Qatar"),
    ),
}
